# Generated by Django 2.2 on 2021-11-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='source_provider',
            field=models.CharField(choices=[('Django', 'Django'), ('Google', 'Google'), ('Facebook', 'Facebook')], default='Django', max_length=15),
        ),
    ]
