# Generated by Django 3.2 on 2021-12-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialauthenticatedusers',
            name='facebook_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialauthenticatedusers',
            name='google_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
